-- ====================================================================================
-- BASE DE DATOS: Sistema para una Tienda Digital de Música y Podcast
--
-- ESTUDIANTES:
--   Eduardo David González González
--   Alberto Zúñiga Sánchez
--   Jean Paul Segura Villalobos
--   Edgar Fabián Mora Hidalgo
--
-- UNIVERSIDAD FIDÉLITAS
-- CURSO: SC-404 Fundamentos de Diseño de Base de Datos
-- PROFESOR: Robles Sánchez Michael
-- FECHA: Junio 30, 2025
-- ====================================================================================

-- ====================================================================================
-- Inserción de datos usando los procedimientos
-- ====================================================================================

-- Inserción de Roles
EXEC PRDB_Insertar_Rol @ID_Rol = 1, @nombre_rol = N'Administrador';
EXEC PRDB_Insertar_Rol @ID_Rol = 2, @nombre_rol = N'Usuario';
EXEC PRDB_Insertar_Rol @ID_Rol = 3, @nombre_rol = N'Moderador';

-- Inserción de Usuarios
EXEC PRDB_Insertar_Usuario 1, 'Carlos', 'Álvarez', 'carlos.alvarez@email.com', 'carlos25', '2024-06-29', 1;
EXEC PRDB_Insertar_Usuario 2, 'José', 'Fernández', 'jose.fernandez@email.com', 'jose123', '2024-06-29', 1;
EXEC PRDB_Insertar_Usuario 3, 'Karina', 'López', 'karina.lopez@email.com', 'lopez58', '2024-06-30', 2;
EXEC PRDB_Insertar_Usuario 4, 'María', 'García', 'maria.garcia@email.com', 'maria456', '2024-07-01', 1;
EXEC PRDB_Insertar_Usuario 5, 'Luis', 'Rodríguez', 'luis.rodriguez@email.com', 'luis789', '2024-07-02', 1;
EXEC PRDB_Insertar_Usuario 6, 'Ana', 'Martínez', 'ana.martinez@email.com', 'ana012', '2024-07-03', 3;
EXEC PRDB_Insertar_Usuario 7, 'Pedro', 'Sánchez', 'pedro.sanchez@email.com', 'pedro345', '2024-07-04', 1;
EXEC PRDB_Insertar_Usuario 8, 'Laura', 'Jiménez', 'laura.jimenez@email.com', 'laura678', '2024-07-05', 1;
EXEC PRDB_Insertar_Usuario 9, 'Miguel', 'Ruiz', 'miguel.ruiz@email.com', 'miguel901', '2024-07-06', 1;
EXEC PRDB_Insertar_Usuario 10, 'Carmen', 'Torres', 'carmen.torres@email.com', 'carmen234', '2024-07-07', 2;
EXEC PRDB_Insertar_Usuario 11, 'Diego', 'Morales', 'diego.morales@email.com', 'diego567', '2024-07-08', 1;
EXEC PRDB_Insertar_Usuario 12, 'Sofía', 'Herrera', 'sofia.herrera@email.com', 'sofia890', '2024-07-09', 1;
EXEC PRDB_Insertar_Usuario 13, 'Javier', 'Mendoza', 'javier.mendoza@email.com', 'javier123', '2024-07-10', 3;
EXEC PRDB_Insertar_Usuario 14, 'Elena', 'Castro', 'elena.castro@email.com', 'elena456', '2024-07-11', 1;
EXEC PRDB_Insertar_Usuario 15, 'Roberto', 'Vargas', 'roberto.vargas@email.com', 'roberto789', '2024-07-12', 1;
EXEC PRDB_Insertar_Usuario 16, 'Lucía', 'Ramírez', 'lucia.ramirez@email.com', 'lucia012', '2024-07-13', 1;
EXEC PRDB_Insertar_Usuario 17, 'Antonio', 'Flores', 'antonio.flores@email.com', 'antonio345', '2024-07-14', 2;
EXEC PRDB_Insertar_Usuario 18, 'Isabel', 'Ortega', 'isabel.ortega@email.com', 'isabel678', '2024-07-15', 1;
EXEC PRDB_Insertar_Usuario 19, 'Fernando', 'Delgado', 'fernando.delgado@email.com', 'fernando901', '2024-07-16', 1;
EXEC PRDB_Insertar_Usuario 20, 'Cristina', 'Vega', 'cristina.vega@email.com', 'cristina234', '2024-07-17', 1;
EXEC PRDB_Insertar_Usuario 21, 'Álvaro', 'Campos', 'alvaro.campos@email.com', 'alvaro567', '2024-07-18', 3;
EXEC PRDB_Insertar_Usuario 22, 'Mónica', 'Navarro', 'monica.navarro@email.com', 'monica890', '2024-07-19', 1;
EXEC PRDB_Insertar_Usuario 23, 'Sergio', 'Cano', 'sergio.cano@email.com', 'sergio123', '2024-07-20', 1;
EXEC PRDB_Insertar_Usuario 24, 'Devis', 'Garcia', 'devis.garcia@email.com', 'devis456', '2024-07-21', 1;
EXEC PRDB_Insertar_Usuario 25, 'Raúl', 'Lozano', 'raul.lozano@email.com', 'raul789', '2024-07-22', 1;
EXEC PRDB_Insertar_Usuario 26, 'Nuria', 'Guerrero', 'nuria.guerrero@email.com', 'nuria012', '2024-07-23', 2;
EXEC PRDB_Insertar_Usuario 27, 'Óscar', 'Cortés', 'oscar.cortes@email.com', 'oscar345', '2024-07-24', 1;
EXEC PRDB_Insertar_Usuario 28, 'Rocío', 'Serrano', 'rocio.serrano@email.com', 'rocio678', '2024-07-25', 1;
EXEC PRDB_Insertar_Usuario 29, 'Iván', 'Peña', 'ivan.pena@email.com', 'ivan901', '2024-07-26', 1;
EXEC PRDB_Insertar_Usuario 30, 'Silvia', 'Aguilar', 'silvia.aguilar@email.com', 'silvia234', '2024-07-27', 1;
EXEC PRDB_Insertar_Usuario 31, 'Adrián', 'Bravo', 'adrian.bravo@email.com', 'adrian567', '2024-07-28', 3;
EXEC PRDB_Insertar_Usuario 32, 'Verónica', 'Gallego', 'veronica.gallego@email.com', 'veronica890', '2024-07-29', 1;
EXEC PRDB_Insertar_Usuario 33, 'Marcos', 'León', 'marcos.leon@email.com', 'marcos123', '2024-07-30', 1;
EXEC PRDB_Insertar_Usuario 34, 'Patricia', 'Marín', 'patricia.marin@email.com', 'patricia456', '2024-07-31', 1;
EXEC PRDB_Insertar_Usuario 35, 'Víctor', 'Santos', 'victor.santos@email.com', 'victor789', '2024-08-01', 1;
EXEC PRDB_Insertar_Usuario 36, 'Joshua', 'Soto', 'joshua.soto@email.com', 'joshua012', '2024-08-02', 2;
EXEC PRDB_Insertar_Usuario 37, 'Gonzalo', 'Muñoz', 'gonzalo.munoz@email.com', 'gonzalo345', '2024-08-03', 1;
EXEC PRDB_Insertar_Usuario 38, 'Anthony', 'Caballero', 'tony.caballero@email.com', 'tony678', '2024-08-04', 1;
EXEC PRDB_Insertar_Usuario 39, 'Emilio', 'Nieto', 'emilio.nieto@email.com', 'emilio901', '2024-08-05', 1;
EXEC PRDB_Insertar_Usuario 40, 'Esperanza', 'Domínguez', 'esperanza.dominguez@email.com', 'esperanza234', '2024-08-06', 1;
EXEC PRDB_Insertar_Usuario 41, 'Alejandro', 'Fuentes', 'alejandro.fuentes@email.com', 'alejandro567', '2024-08-07', 1;
EXEC PRDB_Insertar_Usuario 42, 'Dolores', 'Ramos', 'dolores.ramos@email.com', 'dolores890', '2024-08-08', 3;
EXEC PRDB_Insertar_Usuario 43, 'Manuel', 'Soto', 'manuel.soto@email.com', 'manuel123', '2024-08-09', 1;
EXEC PRDB_Insertar_Usuario 44, 'Pilar', 'Blanco', 'pilar.blanco@email.com', 'pilar456', '2024-08-10', 1;
EXEC PRDB_Insertar_Usuario 45, 'Francisco', 'Pascual', 'francisco.pascual@email.com', 'francisco789', '2024-08-11', 1;
EXEC PRDB_Insertar_Usuario 46, 'Natalia', 'Gil', 'natalia.gil@email.com', 'natalia012', '2024-08-12', 1;
EXEC PRDB_Insertar_Usuario 47, 'Rubén', 'Medina', 'ruben.medina@email.com', 'ruben345', '2024-08-13', 1;
EXEC PRDB_Insertar_Usuario 48, 'Fiorella', 'Cabrera', 'fiorella.cabrera@email.com', 'fiorella678', '2024-08-14', 2;
EXEC PRDB_Insertar_Usuario 49, 'David', 'Gonzalez', 'david.gonzalez@email.com', 'david901', '2024-08-15', 1;
EXEC PRDB_Insertar_Usuario 50, 'Rosa', 'Molina', 'rosa.molina@email.com', 'rosa234', '2024-08-16', 1;


-- Inserción de Artistas
EXEC PRDB_Insertar_Artista 1, N'Coldplay', N'Chris', N'Martin', N'Reino Unido', N'Banda británica de rock alternativo formada en Londres en 1996.';
EXEC PRDB_Insertar_Artista 2, N'Malpais', N'Fidel', N'Gamboa', N'Costa Rica', N'Banda costarricense de rock alternativo y folk.';
EXEC PRDB_Insertar_Artista 3, N'Percance', N'Esteban', N'Ramírez', N'Costa Rica', N'Grupo musical costarricense de rock alternativo.';
EXEC PRDB_Insertar_Artista 4, N'Adele', N'Adele', N'Adkins', N'Reino Unido', N'Cantante británica reconocida por su poderosa voz y baladas emotivas.';
EXEC PRDB_Insertar_Artista 5, N'Hans Zimmer', N'Hans', N'Zimmer', N'Alemania', N'Compositor alemán de música instrumental y bandas sonoras.';
EXEC PRDB_Insertar_Artista 6, N'Maroon 5', N'Adam', N'Levine', N'Estados Unidos', N'Banda estadounidense de pop rock y funk.';
EXEC PRDB_Insertar_Artista 7, N'Imagine Dragons', N'Dan', N'Reynolds', N'Estados Unidos', N'Banda estadounidense de rock alternativo.';
EXEC PRDB_Insertar_Artista 8, N'Linkin Park', N'Chester', N'Bennington', N'Estados Unidos', N'Banda estadounidense de rock alternativo y nu metal.';
EXEC PRDB_Insertar_Artista 9, N'Bruno Mars', N'Peter', N'Hernandez', N'Estados Unidos', N'Cantante, compositor y productor musical hawaiano.';
EXEC PRDB_Insertar_Artista 10, N'Ed Sheeran', N'Edward', N'Sheeran', N'Reino Unido', N'Cantautor británico de pop y folk.';
EXEC PRDB_Insertar_Artista 11, N'Beyoncé', N'Beyoncé', N'Knowles', N'Estados Unidos', N'Cantante y compositora estadounidense de pop y R&B.';
EXEC PRDB_Insertar_Artista 12, N'99% Invisible', N'Roman', N'Mars', N'Estados Unidos', N'Podcast sobre diseño y arquitectura.';
EXEC PRDB_Insertar_Artista 13, N'Waveform', N'Marques', N'Brownlee', N'Estados Unidos', N'Podcast sobre tecnología conducido por Marques Brownlee.';
EXEC PRDB_Insertar_Artista 14, N'The Daily', N'Michael', N'Barbaro', N'Estados Unidos', N'Podcast de noticias producido por The New York Times.';
EXEC PRDB_Insertar_Artista 15, N'The Bill Simmons Podcast', N'Bill', N'Simmons', N'Estados Unidos', N'Podcast sobre deportes, cultura pop y entrevistas.';
EXEC PRDB_Insertar_Artista 16, N'SmartLess', N'Jason', N'Bateman', N'Estados Unidos', N'Podcast de comedia conducido por Jason Bateman, Sean Hayes y Will Arnett.';
EXEC PRDB_Insertar_Artista 17, N'Men in Blazers', N'Roger', N'Bennett', N'Estados Unidos', N'Podcast de fútbol con enfoque en la Premier League.';
EXEC PRDB_Insertar_Artista 18, N'Radiohead', N'Thom', N'Yorke', N'Reino Unido', N'Banda británica de rock alternativo.';
EXEC PRDB_Insertar_Artista 19, N'The Beatles', N'John', N'Lennon', N'Reino Unido', N'Legendaria banda británica de rock y pop.';
EXEC PRDB_Insertar_Artista 20, N'Pink Floyd', N'David', N'Gilmour', N'Reino Unido', N'Banda británica de rock progresivo.';
EXEC PRDB_Insertar_Artista 21, N'Led Zeppelin', N'Robert', N'Plant', N'Reino Unido', N'Banda británica de hard rock.';
EXEC PRDB_Insertar_Artista 22, N'Queen', N'Freddie', N'Mercury', N'Reino Unido', N'Banda británica de rock.';
EXEC PRDB_Insertar_Artista 23, N'U2', N'Bono', N'Vox', N'Irlanda', N'Banda irlandesa de rock.';
EXEC PRDB_Insertar_Artista 24, N'Nirvana', N'Kurt', N'Cobain', N'Estados Unidos', N'Banda estadounidense de grunge.';
EXEC PRDB_Insertar_Artista 25, N'Pearl Jam', N'Eddie', N'Vedder', N'Estados Unidos', N'Banda estadounidense de rock alternativo.';
EXEC PRDB_Insertar_Artista 26, N'Muse', N'Matthew', N'Bellamy', N'Reino Unido', N'Banda británica de rock alternativo.';
EXEC PRDB_Insertar_Artista 27, N'Arctic Monkeys', N'Alex', N'Turner', N'Reino Unido', N'Banda británica de rock alternativo.';
EXEC PRDB_Insertar_Artista 28, N'The Strokes', N'Julian', N'Casablancas', N'Estados Unidos', N'Banda estadounidense de rock alternativo.';
EXEC PRDB_Insertar_Artista 29, N'Foo Fighters', N'Dave', N'Grohl', N'Estados Unidos', N'Banda estadounidense de rock alternativo.';
EXEC PRDB_Insertar_Artista 30, N'Red Hot Chili Peppers', N'Anthony', N'Kiedis', N'Estados Unidos', N'Banda estadounidense de funk rock.';
EXEC PRDB_Insertar_Artista 31, N'Hardcore History', N'Dan', N'Carlin', N'Estados Unidos', N'Podcast educativo sobre historia mundial.';
EXEC PRDB_Insertar_Artista 32, N'Imaginary Worlds', N'Eric', N'Molinsky', N'Estados Unidos', N'Podcast sobre ciencia ficción y fantasía.';
EXEC PRDB_Insertar_Artista 33, N'Classical Performance', N'Maria', N'López', N'Estados Unidos', N'Podcast dedicado a la música clásica.';
EXEC PRDB_Insertar_Artista 34, N'Philosophize This!', N'Stephen', N'West', N'Estados Unidos', N'Podcast sobre corrientes filosóficas contemporáneas.';
EXEC PRDB_Insertar_Artista 35, N'Planet Money', N'Jacob', N'Goldstein', N'Estados Unidos', N'Podcast sobre economía y finanzas.';
EXEC PRDB_Insertar_Artista 36, N'The Happiness Lab', N'Laurie', N'Santos', N'Estados Unidos', N'Podcast sobre psicología y bienestar.';
EXEC PRDB_Insertar_Artista 37, N'Zero To Travel', N'Jason', N'Moore', N'Estados Unidos', N'Podcast sobre viajes y culturas globales.';
EXEC PRDB_Insertar_Artista 38, N'Gastropod', N'Cynthia', N'Graber', N'Estados Unidos', N'Podcast sobre historia y ciencia de la comida.';
EXEC PRDB_Insertar_Artista 39, N'The Art History Babes', N'Corrie', N'Johnson', N'Estados Unidos', N'Podcast sobre arte contemporáneo y clásico.';
EXEC PRDB_Insertar_Artista 40, N'The Candid Frame', N'Ibarionex', N'Perello', N'Estados Unidos', N'Podcast sobre fotografía y creatividad.';
EXEC PRDB_Insertar_Artista 41, N'Indie Film Hustle', N'Alex', N'Ferrari', N'Estados Unidos', N'Podcast sobre cine independiente.';
EXEC PRDB_Insertar_Artista 42, N'Latino USA', N'Maria', N'Hinojosa', N'Estados Unidos', N'Podcast sobre literatura, cultura y sociedad latinoamericana.';
EXEC PRDB_Insertar_Artista 43, N'CityLab Daily', N'Laura', N'Bliss', N'Estados Unidos', N'Podcast sobre ecología y sostenibilidad urbana.';
EXEC PRDB_Insertar_Artista 44, N'How I Built This', N'Guy', N'Raz', N'Estados Unidos', N'Podcast sobre startups y negocios.';
EXEC PRDB_Insertar_Artista 45, N'The Mindful Kind', N'Rachael', N'Kable', N'Estados Unidos', N'Podcast sobre meditación y mindfulness.';
EXEC PRDB_Insertar_Artista 46, N'Game Scoop!', N'Damon', N'Hatfield', N'Estados Unidos', N'Podcast sobre videojuegos y noticias del gaming.';
EXEC PRDB_Insertar_Artista 47, N'StartUp Podcast', N'Alex', N'Blumberg', N'Estados Unidos', N'Podcast sobre emprendedores y tecnología.';
EXEC PRDB_Insertar_Artista 48, N'AnthroPod', N'Savannah', N'Finver', N'Estados Unidos', N'Podcast de antropología del AAA.';
EXEC PRDB_Insertar_Artista 49, N'The Natural Health Podcast', N'Maria', N'Hadji', N'Estados Unidos', N'Podcast sobre medicina natural y bienestar.';
EXEC PRDB_Insertar_Artista 50, N'Green Building Matters', N'Charlie', N'Cichetti', N'Estados Unidos', N'Podcast sobre arquitectura sostenible y ecológica.';

-- Inserción de Albumes
EXEC PRDB_Insertar_Album 1, N'Parachutes', '2000-07-10', N'Álbum debut de Coldplay con un sonido melancólico y minimalista.';
EXEC PRDB_Insertar_Album 2, N'A Rush of Blood to the Head', '2002-08-26', N'Segundo álbum con temas introspectivos y arreglos musicales más complejos.';
EXEC PRDB_Insertar_Album 3, N'X&Y', '2005-06-06', N'Mezcla de sintetizadores y guitarras que explora el existencialismo.';
EXEC PRDB_Insertar_Album 4, N'Viva la Vida', '2008-06-12', N'Fusión de arte barroco y pop alternativo con influencias clásicas.';
EXEC PRDB_Insertar_Album 5, N'Mylo Xyloto', '2011-10-24', N'Conceptual y colorido, con temas sobre libertad y resistencia.';
EXEC PRDB_Insertar_Album 6, N'Ghost Stories', '2014-05-19', N'Tonalidad oscura que explora la pérdida y la introspección.';
EXEC PRDB_Insertar_Album 7, N'A Head Full of Dreams', '2015-12-04', N'Álbum vibrante con una visión optimista y colaboraciones diversas.';
EXEC PRDB_Insertar_Album 8, N'Everyday Life', '2019-11-22', N'Dividido en dos partes, presenta crítica social y diversidad sonora.';
EXEC PRDB_Insertar_Album 9, N'Music of the Spheres', '2021-10-15', N'Inspirado en el universo, con tintes electrónicos y futuristas.';
EXEC PRDB_Insertar_Album 10, N'Un Día Lejano', '2009-03-15', N'Folk costarricense con una narrativa sobre amor y nostalgia.';
EXEC PRDB_Insertar_Album 11, N'Historias de Nadie', '2012-08-20', N'Crónicas sonoras sobre la vida cotidiana en Latinoamérica.';
EXEC PRDB_Insertar_Album 12, N'19', '2008-01-28', N'Debut de Adele que muestra vulnerabilidad emocional y madurez vocal.';
EXEC PRDB_Insertar_Album 13, N'21', '2011-01-24', N'Canciones poderosas sobre desamor y superación.';
EXEC PRDB_Insertar_Album 14, N'25', '2015-11-20', N'Reflexivo y nostálgico, marcando un regreso esperado.';
EXEC PRDB_Insertar_Album 15, N'30', '2021-11-19', N'Crónica íntima del crecimiento personal tras el divorcio.';
EXEC PRDB_Insertar_Album 16, N'Hands All Over', '2010-06-21', N'Pop rock moderno con letras sobre relaciones y deseo.';
EXEC PRDB_Insertar_Album 17, N'Overexposed', '2012-06-20', N'Ritmos bailables y producción digital sofisticada.';
EXEC PRDB_Insertar_Album 18, N'V', '2014-08-29', N'Sonido accesible con hooks pop y funk.';
EXEC PRDB_Insertar_Album 19, N'Red Pill Blues', '2017-11-03', N'Sonido contemporáneo con elementos electrónicos y colaboraciones.';
EXEC PRDB_Insertar_Album 20, N'Jordi', '2021-06-11', N'Álbum homenaje con un enfoque emocional y personal.';
EXEC PRDB_Insertar_Album 21, N'Night Visions', '2012-09-04', N'Exitoso debut de Imagine Dragons con fusión de rock y electrónica.';
EXEC PRDB_Insertar_Album 22, N'Smoke + Mirrors', '2015-02-17', N'Tonos oscuros y líricas introspectivas con arreglos experimentales.';
EXEC PRDB_Insertar_Album 23, N'Evolve', '2017-06-23', N'Temas de transformación personal con beats energéticos.';
EXEC PRDB_Insertar_Album 24, N'Origins', '2018-11-09', N'Continuación estilística de Evolve con énfasis en la identidad.';
EXEC PRDB_Insertar_Album 25, N'Mercury - Act 1', '2021-09-03', N'Temas sobre la pérdida y la aceptación con una atmósfera alternativa.';
EXEC PRDB_Insertar_Album 26, N'Hybrid Theory', '2000-10-24', N'Álbum debut icónico del nu metal con letras crudas y emocionales.';
EXEC PRDB_Insertar_Album 27, N'Meteora', '2003-03-25', N'Evolución sonora con influencias industriales y melódicas.';
EXEC PRDB_Insertar_Album 28, N'Minutes to Midnight', '2007-05-14', N'Cambio hacia un sonido más rock alternativo.';
EXEC PRDB_Insertar_Album 29, N'A Thousand Suns', '2010-09-08', N'Conceptual y político, con narrativa post-apocalíptica.';
EXEC PRDB_Insertar_Album 30, N'Living Things', '2012-06-20', N'Mezcla de electrónica y rock en un enfoque más directo.';
EXEC PRDB_Insertar_Album 31, N'Doo-Wops & Hooligans', '2010-10-04', N'Debut de Bruno Mars con influencias de soul y pop retro.';
EXEC PRDB_Insertar_Album 32, N'Unorthodox Jukebox', '2012-12-07', N'Diversidad de estilos, desde funk hasta R&B clásico.';
EXEC PRDB_Insertar_Album 33, N'24K Magic', '2016-11-18', N'Estilo funky y retro con espíritu festivo.';
EXEC PRDB_Insertar_Album 34, N'An Evening with Silk Sonic', '2021-11-12', N'Colaboración con Anderson .Paak en un homenaje al soul setentero.';
EXEC PRDB_Insertar_Album 35, N'+', '2011-09-09', N'Baladas acústicas sinceras con letras románticas.';
EXEC PRDB_Insertar_Album 36, N'x', '2014-06-20', N'Expansión de su estilo hacia el R&B y pop.';
EXEC PRDB_Insertar_Album 37, N'÷', '2017-03-03', N'Fusión de ritmos folk, pop y dance.';
EXEC PRDB_Insertar_Album 38, N'No.6 Collaborations Project', '2019-07-12', N'Álbum colaborativo con diversos artistas del pop y hip hop.';
EXEC PRDB_Insertar_Album 39, N'=', '2021-10-29', N'Composiciones maduras sobre paternidad y crecimiento.';
EXEC PRDB_Insertar_Album 40, N'Dangerously in Love', '2003-06-24', N'Debut solista de Beyoncé con énfasis en R&B y sensualidad.';
EXEC PRDB_Insertar_Album 41, N'B''Day', '2006-09-04', N'Álbum potente con temas sobre empoderamiento y pasión.';
EXEC PRDB_Insertar_Album 42, N'I Am... Sasha Fierce', '2008-11-18', N'Dualidad artística entre sensibilidad y fuerza escénica.';
EXEC PRDB_Insertar_Album 43, N'4', '2011-06-24', N'Influencias soul y pop clásico con vocales intensas.';
EXEC PRDB_Insertar_Album 44, N'Lemonade', '2016-04-23', N'Visual y emocional, con crítica social y tono confesional.';
EXEC PRDB_Insertar_Album 45, N'OK Computer', '1997-06-16', N'Hito del rock alternativo con líricas distópicas.';
EXEC PRDB_Insertar_Album 46, N'Kid A', '2000-10-02', N'Experimental y abstracto, alejándose del sonido convencional.';
EXEC PRDB_Insertar_Album 47, N'In Rainbows', '2007-10-10', N'Álbum innovador tanto en distribución como estilo.';
EXEC PRDB_Insertar_Album 48, N'Abbey Road', '1969-09-26', N'Obra icónica de The Beatles con un lado B legendario.';
EXEC PRDB_Insertar_Album 49, N'Sgt. Pepper''s Lonely Hearts Club Band', '1967-06-01', N'Psicodelia, narrativa y producción revolucionaria.';
EXEC PRDB_Insertar_Album 50, N'The Dark Side of the Moon', '1973-03-01', N'Conceptual, introspectivo y una obra maestra del rock progresivo.';

-- Inserción de Canciones
EXEC PRDB_Insertar_Cancion 1, N'Yellow', '00:04:29', 1;
EXEC PRDB_Insertar_Cancion 2, N'The Scientist', '00:05:09', 2;
EXEC PRDB_Insertar_Cancion 3, N'Clocks', '00:05:07', 2;
EXEC PRDB_Insertar_Cancion 4, N'Fix You', '00:04:54', 3;
EXEC PRDB_Insertar_Cancion 5, N'Viva la Vida', '00:04:01', 4;
EXEC PRDB_Insertar_Cancion 6, N'Paradise', '00:04:38', 5;
EXEC PRDB_Insertar_Cancion 7, N'A Sky Full of Stars', '00:04:28', 6;
EXEC PRDB_Insertar_Cancion 8, N'Adventure of a Lifetime', '00:04:23', 7;
EXEC PRDB_Insertar_Cancion 9, N'Hymn for the Weekend', '00:04:18', 7;
EXEC PRDB_Insertar_Cancion 10, N'Something Just Like This', '00:04:07', 8;
EXEC PRDB_Insertar_Cancion 11, N'Rosa de los Vientos', '00:04:15', 10;
EXEC PRDB_Insertar_Cancion 12, N'Muchacha y Luna', '00:03:42', 11;
EXEC PRDB_Insertar_Cancion 13, N'Someone Like You', '00:04:45', 13;
EXEC PRDB_Insertar_Cancion 14, N'Rolling in the Deep', '00:03:48', 13;
EXEC PRDB_Insertar_Cancion 15, N'Set Fire to the Rain', '00:04:01', 13;
EXEC PRDB_Insertar_Cancion 16, N'Hello', '00:04:55', 14;
EXEC PRDB_Insertar_Cancion 17, N'Send My Love', '00:03:43', 14;
EXEC PRDB_Insertar_Cancion 18, N'Easy On Me', '00:03:44', 15;
EXEC PRDB_Insertar_Cancion 19, N'Moves Like Jagger', '00:03:21', 16;
EXEC PRDB_Insertar_Cancion 20, N'Payphone', '00:03:51', 17;
EXEC PRDB_Insertar_Cancion 21, N'Animals', '00:03:51', 18;
EXEC PRDB_Insertar_Cancion 22, N'Sugar', '00:03:55', 18;
EXEC PRDB_Insertar_Cancion 23, N'Don''t Wanna Know', '00:03:34', 19;
EXEC PRDB_Insertar_Cancion 24, N'Cold', '00:03:41', 20;
EXEC PRDB_Insertar_Cancion 25, N'Radioactive', '00:03:06', 21;
EXEC PRDB_Insertar_Cancion 26, N'Demons', '00:02:57', 21;
EXEC PRDB_Insertar_Cancion 27, N'Believer', '00:03:24', 23;
EXEC PRDB_Insertar_Cancion 28, N'Thunder', '00:03:07', 23;
EXEC PRDB_Insertar_Cancion 29, N'Whatever It Takes', '00:03:21', 23;
EXEC PRDB_Insertar_Cancion 30, N'Natural', '00:03:09', 24;
EXEC PRDB_Insertar_Cancion 31, N'In the End', '00:03:36', 26;
EXEC PRDB_Insertar_Cancion 32, N'Numb', '00:03:07', 27;
EXEC PRDB_Insertar_Cancion 33, N'What I''ve Done', '00:03:25', 28;
EXEC PRDB_Insertar_Cancion 34, N'New Divide', '00:04:28', 28;
EXEC PRDB_Insertar_Cancion 35, N'Burn It Down', '00:03:50', 30;
EXEC PRDB_Insertar_Cancion 36, N'Heavy', '00:02:49', 30;
EXEC PRDB_Insertar_Cancion 37, N'Just the Way You Are', '00:03:40', 31;
EXEC PRDB_Insertar_Cancion 38, N'Grenade', '00:03:42', 31;
EXEC PRDB_Insertar_Cancion 39, N'The Lazy Song', '00:03:15', 31;
EXEC PRDB_Insertar_Cancion 40, N'Locked Out of Heaven', '00:03:53', 32;
EXEC PRDB_Insertar_Cancion 41, N'When I Was Your Man', '00:03:33', 32;
EXEC PRDB_Insertar_Cancion 42, N'Uptown Funk', '00:04:30', 33;
EXEC PRDB_Insertar_Cancion 43, N'24K Magic', '00:03:46', 33;
EXEC PRDB_Insertar_Cancion 44, N'That''s What I Like', '00:03:26', 33;
EXEC PRDB_Insertar_Cancion 45, N'The A Team', '00:04:18', 35;
EXEC PRDB_Insertar_Cancion 46, N'Thinking Out Loud', '00:04:41', 36;
EXEC PRDB_Insertar_Cancion 47, N'Shape of You', '00:03:53', 37;
EXEC PRDB_Insertar_Cancion 48, N'Perfect', '00:04:23', 37;
EXEC PRDB_Insertar_Cancion 49, N'Bad Habits', '00:03:51', 39;
EXEC PRDB_Insertar_Cancion 50, N'Shivers', '00:03:27', 39;

-- Inserción de Podcast
EXEC PRDB_Insertar_Podcast 1, N'99% Invisible', N'Podcast sobre diseño, arquitectura y las historias no contadas que dan forma a nuestro mundo.', N'Diseño';
EXEC PRDB_Insertar_Podcast 2, N'Waveform', N'Podcast semanal sobre la última tecnología con Marques Brownlee.', N'Tecnología';
EXEC PRDB_Insertar_Podcast 3, N'The Daily', N'Podcast diario de noticias del New York Times.', N'Noticias';
EXEC PRDB_Insertar_Podcast 4, N'The Bill Simmons Podcast', N'Deportes, cultura pop y conversaciones con invitados especiales.', N'Cultura pop';
EXEC PRDB_Insertar_Podcast 5, N'SmartLess', N'Podcast de comedia con Jason Bateman, Sean Hayes y Will Arnett.', N'Comedia';
EXEC PRDB_Insertar_Podcast 6, N'Men in Blazers', N'Podcast sobre fútbol con enfoque en la Premier League.', N'Deportes';
EXEC PRDB_Insertar_Podcast 7, N'Hardcore History', N'Podcast educativo sobre eventos históricos fascinantes.', N'Historia';
EXEC PRDB_Insertar_Podcast 8, N'Imaginary Worlds', N'Podcast sobre ciencia ficción, fantasía y cómo crear mundos imaginarios.', N'Ficción';
EXEC PRDB_Insertar_Podcast 9, N'Classical Performance', N'Podcast dedicado a la música clásica y las mejores interpretaciones.', N'Música';
EXEC PRDB_Insertar_Podcast 10, N'Philosophize This!', N'Podcast sobre filosofía y pensadores contemporáneos.', N'Educación';
EXEC PRDB_Insertar_Podcast 11, N'Planet Money', N'Podcast sobre economía que hace que las finanzas sean comprensibles.', N'Economía';
EXEC PRDB_Insertar_Podcast 12, N'The Happiness Lab', N'Podcast sobre la ciencia de la felicidad y el bienestar.', N'Salud mental';
EXEC PRDB_Insertar_Podcast 13, N'Zero To Travel', N'Podcast sobre viajes y culturas del mundo.', N'Viajes';
EXEC PRDB_Insertar_Podcast 14, N'Gastropod', N'Podcast sobre la historia y ciencia detrás de la comida.', N'Gastronomía';
EXEC PRDB_Insertar_Podcast 15, N'The Art History Babes', N'Podcast sobre arte, desde lo clásico hasta lo contemporáneo.', N'Arte';
EXEC PRDB_Insertar_Podcast 16, N'The Candid Frame', N'Podcast sobre fotografía y la búsqueda de la creatividad.', N'Fotografía';
EXEC PRDB_Insertar_Podcast 17, N'Indie Film Hustle', N'Podcast sobre la industria del cine independiente.', N'Cine';
EXEC PRDB_Insertar_Podcast 18, N'Latino USA', N'Podcast sobre literatura, cultura y sociedad latinoamericana.', N'Cultura';
EXEC PRDB_Insertar_Podcast 19, N'CityLab Daily', N'Podcast sobre sostenibilidad urbana y ecología.', N'Ecología';
EXEC PRDB_Insertar_Podcast 20, N'How I Built This', N'Podcast sobre emprendedores y cómo construyeron sus empresas.', N'Negocios';
EXEC PRDB_Insertar_Podcast 21, N'The Mindful Kind', N'Podcast sobre meditación, mindfulness y bienestar mental.', N'Bienestar';
EXEC PRDB_Insertar_Podcast 22, N'Game Scoop!', N'Podcast sobre videojuegos y las últimas noticias del gaming.', N'Videojuegos';
EXEC PRDB_Insertar_Podcast 23, N'StartUp Podcast', N'Podcast sobre startups y el mundo de la tecnología.', N'Emprendimiento';
EXEC PRDB_Insertar_Podcast 24, N'AnthroPod', N'Podcast de antropología producido por la AAA.', N'Ciencia';
EXEC PRDB_Insertar_Podcast 25, N'Natural Health Podcast', N'Podcast sobre medicina natural y alternativas de bienestar.', N'Salud';
EXEC PRDB_Insertar_Podcast 26, N'Green Building Matters', N'Podcast sobre arquitectura sostenible y construcción ecológica.', N'Arquitectura';
EXEC PRDB_Insertar_Podcast 27, N'Tech Talk Daily', N'Podcast diario sobre las últimas noticias tecnológicas.', N'Tecnología';
EXEC PRDB_Insertar_Podcast 28, N'The Science Hour', N'Podcast semanal sobre descubrimientos científicos.', N'Ciencia';
EXEC PRDB_Insertar_Podcast 29, N'Modern Love', N'Podcast sobre relaciones y amor en la era moderna.', N'Relaciones';
EXEC PRDB_Insertar_Podcast 30, N'Criminal', N'Podcast sobre crímenes reales y casos fascinantes.', N'Crimen real';
EXEC PRDB_Insertar_Podcast 31, N'Reply All', N'Podcast sobre internet y cultura digital.', N'Tecnología';
EXEC PRDB_Insertar_Podcast 32, N'The Joe Rogan Experience', N'Podcast de conversaciones largas con invitados diversos.', N'Entrevistas';
EXEC PRDB_Insertar_Podcast 33, N'Serial', N'Podcast investigativo sobre casos criminales.', N'Crimen real';
EXEC PRDB_Insertar_Podcast 34, N'This American Life', N'Podcast sobre historias extraordinarias de la vida ordinaria.', N'Narrativa';
EXEC PRDB_Insertar_Podcast 35, N'Radiolab', N'Podcast sobre ciencia, filosofía y experiencia humana.', N'Ciencia';
EXEC PRDB_Insertar_Podcast 36, N'The Tim Ferriss Show', N'Podcast sobre productividad y alto rendimiento.', N'Productividad';
EXEC PRDB_Insertar_Podcast 37, N'Conan O''Brien Needs a Friend', N'Podcast de comedia con Conan O''Brien.', N'Comedia';
EXEC PRDB_Insertar_Podcast 38, N'My Favorite Murder', N'Podcast sobre crímenes reales con un toque de comedia.', N'Crimen real';
EXEC PRDB_Insertar_Podcast 39, N'The History of Rome', N'Podcast sobre la historia del Imperio Romano.', N'Historia';
EXEC PRDB_Insertar_Podcast 40, N'Stuff You Should Know', N'Podcast educativo sobre una amplia variedad de temas.', N'Educación';
EXEC PRDB_Insertar_Podcast 41, N'The Moth', N'Podcast de historias reales contadas en vivo.', N'Narrativa';
EXEC PRDB_Insertar_Podcast 42, N'Hidden Brain', N'Podcast sobre psicología y comportamiento humano.', N'Psicología';
EXEC PRDB_Insertar_Podcast 43, N'Freakonomics Radio', N'Podcast sobre economía y ciencias sociales.', N'Economía';
EXEC PRDB_Insertar_Podcast 44, N'The Nerdist', N'Podcast sobre cultura nerd y entrevistas con celebridades.', N'Entretenimiento';
EXEC PRDB_Insertar_Podcast 45, N'WTF with Marc Maron', N'Podcast de entrevistas con Marc Maron.', N'Entrevistas';
EXEC PRDB_Insertar_Podcast 46, N'Song Exploder', N'Podcast donde músicos descomponen sus canciones.', N'Música';
EXEC PRDB_Insertar_Podcast 47, N'Code Switch', N'Podcast sobre raza y identidad en América.', N'Identidad';
EXEC PRDB_Insertar_Podcast 48, N'The Bright Sessions', N'Podcast de ficción sobre terapia para personas con habilidades sobrenaturales.', N'Ficción';
EXEC PRDB_Insertar_Podcast 49, N'Welcome to Night Vale', N'Podcast de ficción sobre una ciudad extraña del desierto.', N'Ficción';
EXEC PRDB_Insertar_Podcast 50, N'Limetown', N'Podcast de ficción sobre una investigación de una ciudad desaparecida.', N'Ficción';

-- Inserción de Episodios
EXEC PRDB_Insertar_Episodio 1, N'The Hidden World of Design', '2020-01-15', '00:28:15', 1;
EXEC PRDB_Insertar_Episodio 2, N'Sound and Space', '2020-02-12', '00:30:03', 1;
EXEC PRDB_Insertar_Episodio 3, N'Invisible Infrastructure', '2020-03-18', '00:32:40', 1;
EXEC PRDB_Insertar_Episodio 4, N'99% Music', '2020-04-15', '00:29:10', 1;
EXEC PRDB_Insertar_Episodio 5, N'Architectural Secrets', '2020-05-20', '00:33:00', 1;
EXEC PRDB_Insertar_Episodio 6, N'Apple vs Samsung 2023', '2023-02-01', '00:36:24', 2;
EXEC PRDB_Insertar_Episodio 7, N'Best Budget Phones', '2023-03-01', '00:34:17', 2;
EXEC PRDB_Insertar_Episodio 8, N'Foldables: Future or Flop?', '2023-04-01', '00:35:45', 2;
EXEC PRDB_Insertar_Episodio 9, N'AI in Everyday Life', '2023-05-01', '00:37:08', 2;
EXEC PRDB_Insertar_Episodio 10, N'WWDC Reactions', '2023-06-01', '00:39:55', 2;
EXEC PRDB_Insertar_Episodio 11, N'Breaking News: Elections 2024', '2024-01-04', '00:20:00', 3;
EXEC PRDB_Insertar_Episodio 12, N'Conflict in Europe', '2024-01-05', '00:18:40', 3;
EXEC PRDB_Insertar_Episodio 13, N'Economic Outlook 2024', '2024-01-06', '00:21:22', 3;
EXEC PRDB_Insertar_Episodio 14, N'Interview with LeBron James', '2023-09-15', '00:55:00', 4;
EXEC PRDB_Insertar_Episodio 15, N'NFL Predictions', '2023-10-01', '00:50:00', 4;
EXEC PRDB_Insertar_Episodio 16, N'Sean''s Birthday Special', '2022-08-10', '00:48:22', 5;
EXEC PRDB_Insertar_Episodio 17, N'SmartLess Live: New York', '2022-08-17', '00:52:17', 5;
EXEC PRDB_Insertar_Episodio 18, N'Pep Guardiola''s Rise', '2023-03-10', '00:40:00', 6;
EXEC PRDB_Insertar_Episodio 19, N'Premier League Roundup', '2023-03-17', '00:45:00', 6;
EXEC PRDB_Insertar_Episodio 20, N'The Mongol Empire', '2021-06-30', '01:15:45', 7;
EXEC PRDB_Insertar_Episodio 21, N'The Fall of Rome', '2021-08-01', '01:20:10', 7;
EXEC PRDB_Insertar_Episodio 22, N'World-Building in Sci-Fi', '2020-11-15', '00:42:03', 8;
EXEC PRDB_Insertar_Episodio 23, N'Magic and Metaphor', '2020-12-01', '00:39:59', 8;
EXEC PRDB_Insertar_Episodio 24, N'Bach''s Brilliance', '2019-09-12', '00:47:20', 9;
EXEC PRDB_Insertar_Episodio 25, N'The Art of Interpretation', '2019-10-10', '00:50:00', 9;
EXEC PRDB_Insertar_Episodio 26, N'Socrates in the 21st Century', '2020-03-03', '00:36:00', 10;
EXEC PRDB_Insertar_Episodio 27, N'Nietzsche and Nihilism', '2020-04-14', '00:38:25', 10;
EXEC PRDB_Insertar_Episodio 28, N'How to Buy a House', '2022-05-11', '00:22:15', 11;
EXEC PRDB_Insertar_Episodio 29, N'The Dollar Crisis', '2022-06-15', '00:27:42', 11;
EXEC PRDB_Insertar_Episodio 30, N'What Happiness Really Means', '2022-07-01', '00:33:00', 12;
EXEC PRDB_Insertar_Episodio 31, N'Habits and Joy', '2022-07-15', '00:34:44', 12;
EXEC PRDB_Insertar_Episodio 32, N'Packing for the Unknown', '2023-01-10', '00:26:45', 13;
EXEC PRDB_Insertar_Episodio 33, N'Cultures and Contrasts', '2023-02-15', '00:29:35', 13;
EXEC PRDB_Insertar_Episodio 34, N'Salt: The Unexpected History', '2023-03-01', '00:31:12', 14;
EXEC PRDB_Insertar_Episodio 35, N'Bananas and Botany', '2023-03-15', '00:30:20', 14;
EXEC PRDB_Insertar_Episodio 36, N'Monet and the Modern Eye', '2023-04-01', '00:37:10', 15;
EXEC PRDB_Insertar_Episodio 37, N'Art Deco Dreams', '2023-04-15', '00:35:45', 15;
EXEC PRDB_Insertar_Episodio 38, N'The Mind of a Photographer', '2023-05-01', '00:32:20', 16;
EXEC PRDB_Insertar_Episodio 39, N'Capturing Emotion in Light', '2023-05-15', '00:31:30', 16;
EXEC PRDB_Insertar_Episodio 40, N'How Indies Get Funded', '2023-06-01', '00:40:00', 17;
EXEC PRDB_Insertar_Episodio 41, N'First-Time Filmmaker Tips', '2023-06-15', '00:42:10', 17;
EXEC PRDB_Insertar_Episodio 42, N'Latino Lit: Voices Rising', '2023-07-01', '00:34:22', 18;
EXEC PRDB_Insertar_Episodio 43, N'Rhythms and Resistance', '2023-07-15', '00:33:17', 18;
EXEC PRDB_Insertar_Episodio 44, N'Urban Heat Islands', '2023-08-01', '00:28:50', 19;
EXEC PRDB_Insertar_Episodio 45, N'Building for the Future', '2023-08-15', '00:29:40', 19;
EXEC PRDB_Insertar_Episodio 46, N'Founder Failures', '2023-09-01', '00:37:00', 20;
EXEC PRDB_Insertar_Episodio 47, N'Pivot Points', '2023-09-15', '00:35:12', 20;
EXEC PRDB_Insertar_Episodio 48, N'Meditation Myths', '2023-10-01', '00:26:35', 21;
EXEC PRDB_Insertar_Episodio 49, N'The Mind-Body Link', '2023-10-15', '00:27:20', 21;
EXEC PRDB_Insertar_Episodio 50, N'The Rise of Esports', '2023-11-01', '00:39:10', 22;

-- Inserción de Suscripciones
EXEC PRDB_Insertar_Suscripcion 1, 'Bronce', 5000.00;
EXEC PRDB_Insertar_Suscripcion 2, 'Plata', 7000.00;
EXEC PRDB_Insertar_Suscripcion 3, 'Oro', 10000.00;

-- Inserción de Pagos
EXEC PRDB_Insertar_Pago_Suscripcion 1, 1, '2024-06-15';
EXEC PRDB_Insertar_Pago_Suscripcion 2, 2, '2025-01-10';
EXEC PRDB_Insertar_Pago_Suscripcion 3, 3, '2024-12-01';
EXEC PRDB_Insertar_Pago_Suscripcion 4, 1, '2025-03-22';
EXEC PRDB_Insertar_Pago_Suscripcion 5, 2, '2025-06-08';
EXEC PRDB_Insertar_Pago_Suscripcion 6, 3, '2024-11-17';
EXEC PRDB_Insertar_Pago_Suscripcion 7, 2, '2025-05-04';
EXEC PRDB_Insertar_Pago_Suscripcion 8, 1, '2024-08-23';
EXEC PRDB_Insertar_Pago_Suscripcion 9, 3, '2025-02-13';
EXEC PRDB_Insertar_Pago_Suscripcion 10, 1, '2024-09-05';
EXEC PRDB_Insertar_Pago_Suscripcion 11, 2, '2025-04-11';
EXEC PRDB_Insertar_Pago_Suscripcion 12, 3, '2024-10-10';
EXEC PRDB_Insertar_Pago_Suscripcion 13, 1, '2025-01-25';
EXEC PRDB_Insertar_Pago_Suscripcion 14, 3, '2025-03-09';
EXEC PRDB_Insertar_Pago_Suscripcion 15, 2, '2024-12-20';
EXEC PRDB_Insertar_Pago_Suscripcion 16, 1, '2024-11-01';
EXEC PRDB_Insertar_Pago_Suscripcion 17, 2, '2025-07-01';
EXEC PRDB_Insertar_Pago_Suscripcion 18, 3, '2025-06-14';
EXEC PRDB_Insertar_Pago_Suscripcion 19, 2, '2024-07-19';
EXEC PRDB_Insertar_Pago_Suscripcion 20, 1, '2025-04-03';
EXEC PRDB_Insertar_Pago_Suscripcion 21, 3, '2025-02-28';
EXEC PRDB_Insertar_Pago_Suscripcion 22, 1, '2024-10-18';
EXEC PRDB_Insertar_Pago_Suscripcion 23, 2, '2025-06-21';
EXEC PRDB_Insertar_Pago_Suscripcion 24, 1, '2025-05-15';
EXEC PRDB_Insertar_Pago_Suscripcion 25, 3, '2024-12-30';
EXEC PRDB_Insertar_Pago_Suscripcion 26, 2, '2024-08-12';
EXEC PRDB_Insertar_Pago_Suscripcion 27, 1, '2025-07-01';
EXEC PRDB_Insertar_Pago_Suscripcion 28, 3, '2025-01-11';
EXEC PRDB_Insertar_Pago_Suscripcion 29, 2, '2024-11-28';
EXEC PRDB_Insertar_Pago_Suscripcion 30, 1, '2025-03-30';
EXEC PRDB_Insertar_Pago_Suscripcion 31, 3, '2024-07-25';
EXEC PRDB_Insertar_Pago_Suscripcion 32, 1, '2024-09-17';
EXEC PRDB_Insertar_Pago_Suscripcion 33, 2, '2025-02-08';
EXEC PRDB_Insertar_Pago_Suscripcion 34, 3, '2024-10-27';
EXEC PRDB_Insertar_Pago_Suscripcion 35, 2, '2025-06-02';
EXEC PRDB_Insertar_Pago_Suscripcion 36, 1, '2025-01-19';
EXEC PRDB_Insertar_Pago_Suscripcion 37, 3, '2025-05-28';
EXEC PRDB_Insertar_Pago_Suscripcion 38, 2, '2024-12-05';
EXEC PRDB_Insertar_Pago_Suscripcion 39, 1, '2024-07-03';
EXEC PRDB_Insertar_Pago_Suscripcion 40, 2, '2025-04-24';
EXEC PRDB_Insertar_Pago_Suscripcion 41, 3, '2025-07-12';
EXEC PRDB_Insertar_Pago_Suscripcion 42, 1, '2025-02-16';
EXEC PRDB_Insertar_Pago_Suscripcion 43, 2, '2024-09-21';
EXEC PRDB_Insertar_Pago_Suscripcion 44, 3, '2025-03-02';
EXEC PRDB_Insertar_Pago_Suscripcion 45, 2, '2025-06-30';
EXEC PRDB_Insertar_Pago_Suscripcion 46, 1, '2024-10-03';
EXEC PRDB_Insertar_Pago_Suscripcion 47, 2, '2025-05-09';
EXEC PRDB_Insertar_Pago_Suscripcion 48, 3, '2025-01-05';
EXEC PRDB_Insertar_Pago_Suscripcion 49, 1, '2024-08-14';
EXEC PRDB_Insertar_Pago_Suscripcion 50, 2, '2025-04-17';

-- Inserción de Canciones escuchadas
EXEC PRDB_Insertar_Canciones_Escuchadas 1, 14;
EXEC PRDB_Insertar_Canciones_Escuchadas 2, 3;
EXEC PRDB_Insertar_Canciones_Escuchadas 3, 27;
EXEC PRDB_Insertar_Canciones_Escuchadas 4, 11;
EXEC PRDB_Insertar_Canciones_Escuchadas 5, 18;
EXEC PRDB_Insertar_Canciones_Escuchadas 6, 9;
EXEC PRDB_Insertar_Canciones_Escuchadas 7, 34;
EXEC PRDB_Insertar_Canciones_Escuchadas 8, 2;
EXEC PRDB_Insertar_Canciones_Escuchadas 9, 30;
EXEC PRDB_Insertar_Canciones_Escuchadas 10, 17;
EXEC PRDB_Insertar_Canciones_Escuchadas 11, 7;
EXEC PRDB_Insertar_Canciones_Escuchadas 12, 42;
EXEC PRDB_Insertar_Canciones_Escuchadas 13, 6;
EXEC PRDB_Insertar_Canciones_Escuchadas 14, 16;
EXEC PRDB_Insertar_Canciones_Escuchadas 15, 4;
EXEC PRDB_Insertar_Canciones_Escuchadas 16, 33;
EXEC PRDB_Insertar_Canciones_Escuchadas 17, 50;
EXEC PRDB_Insertar_Canciones_Escuchadas 18, 8;
EXEC PRDB_Insertar_Canciones_Escuchadas 19, 22;
EXEC PRDB_Insertar_Canciones_Escuchadas 20, 13;
EXEC PRDB_Insertar_Canciones_Escuchadas 21, 45;
EXEC PRDB_Insertar_Canciones_Escuchadas 22, 24;
EXEC PRDB_Insertar_Canciones_Escuchadas 23, 10;
EXEC PRDB_Insertar_Canciones_Escuchadas 24, 36;
EXEC PRDB_Insertar_Canciones_Escuchadas 25, 1;
EXEC PRDB_Insertar_Canciones_Escuchadas 26, 44;
EXEC PRDB_Insertar_Canciones_Escuchadas 27, 15;
EXEC PRDB_Insertar_Canciones_Escuchadas 28, 21;
EXEC PRDB_Insertar_Canciones_Escuchadas 29, 19;
EXEC PRDB_Insertar_Canciones_Escuchadas 30, 35;
EXEC PRDB_Insertar_Canciones_Escuchadas 31, 25;
EXEC PRDB_Insertar_Canciones_Escuchadas 32, 41;
EXEC PRDB_Insertar_Canciones_Escuchadas 33, 12;
EXEC PRDB_Insertar_Canciones_Escuchadas 34, 23;
EXEC PRDB_Insertar_Canciones_Escuchadas 35, 40;
EXEC PRDB_Insertar_Canciones_Escuchadas 36, 28;
EXEC PRDB_Insertar_Canciones_Escuchadas 37, 5;
EXEC PRDB_Insertar_Canciones_Escuchadas 38, 32;
EXEC PRDB_Insertar_Canciones_Escuchadas 39, 38;
EXEC PRDB_Insertar_Canciones_Escuchadas 40, 43;
EXEC PRDB_Insertar_Canciones_Escuchadas 41, 46;
EXEC PRDB_Insertar_Canciones_Escuchadas 42, 20;
EXEC PRDB_Insertar_Canciones_Escuchadas 43, 26;
EXEC PRDB_Insertar_Canciones_Escuchadas 44, 29;
EXEC PRDB_Insertar_Canciones_Escuchadas 45, 31;
EXEC PRDB_Insertar_Canciones_Escuchadas 46, 47;
EXEC PRDB_Insertar_Canciones_Escuchadas 47, 48;
EXEC PRDB_Insertar_Canciones_Escuchadas 48, 39;
EXEC PRDB_Insertar_Canciones_Escuchadas 49, 49;
EXEC PRDB_Insertar_Canciones_Escuchadas 50, 37;

-- Inserción de Episodios vistos
EXEC PRDB_Insertar_Episodios_Vistos 1, 3;
EXEC PRDB_Insertar_Episodios_Vistos 2, 1;
EXEC PRDB_Insertar_Episodios_Vistos 3, 7;
EXEC PRDB_Insertar_Episodios_Vistos 4, 3;
EXEC PRDB_Insertar_Episodios_Vistos 5, 8;
EXEC PRDB_Insertar_Episodios_Vistos 6, 2;
EXEC PRDB_Insertar_Episodios_Vistos 7, 4;
EXEC PRDB_Insertar_Episodios_Vistos 9, 6;
EXEC PRDB_Insertar_Episodios_Vistos 10, 3;
EXEC PRDB_Insertar_Episodios_Vistos 11, 11;
EXEC PRDB_Insertar_Episodios_Vistos 12, 15;
EXEC PRDB_Insertar_Episodios_Vistos 13, 10;
EXEC PRDB_Insertar_Episodios_Vistos 14, 13;
EXEC PRDB_Insertar_Episodios_Vistos 15, 7;
EXEC PRDB_Insertar_Episodios_Vistos 16, 20;
EXEC PRDB_Insertar_Episodios_Vistos 17, 14;
EXEC PRDB_Insertar_Episodios_Vistos 18, 6;
EXEC PRDB_Insertar_Episodios_Vistos 19, 4;
EXEC PRDB_Insertar_Episodios_Vistos 20, 9;
EXEC PRDB_Insertar_Episodios_Vistos 21, 2;
EXEC PRDB_Insertar_Episodios_Vistos 22, 12;
EXEC PRDB_Insertar_Episodios_Vistos 23, 18;
EXEC PRDB_Insertar_Episodios_Vistos 24, 21;
EXEC PRDB_Insertar_Episodios_Vistos 25, 5;
EXEC PRDB_Insertar_Episodios_Vistos 26, 16;
EXEC PRDB_Insertar_Episodios_Vistos 27, 8;
EXEC PRDB_Insertar_Episodios_Vistos 28, 25;
EXEC PRDB_Insertar_Episodios_Vistos 30, 27;
EXEC PRDB_Insertar_Episodios_Vistos 31, 17;
EXEC PRDB_Insertar_Episodios_Vistos 32, 29;
EXEC PRDB_Insertar_Episodios_Vistos 33, 30;
EXEC PRDB_Insertar_Episodios_Vistos 34, 26;
EXEC PRDB_Insertar_Episodios_Vistos 35, 10;
EXEC PRDB_Insertar_Episodios_Vistos 36, 22;
EXEC PRDB_Insertar_Episodios_Vistos 37, 28;
EXEC PRDB_Insertar_Episodios_Vistos 38, 19;
EXEC PRDB_Insertar_Episodios_Vistos 39, 24;
EXEC PRDB_Insertar_Episodios_Vistos 40, 32;
EXEC PRDB_Insertar_Episodios_Vistos 41, 35;
EXEC PRDB_Insertar_Episodios_Vistos 42, 38;
EXEC PRDB_Insertar_Episodios_Vistos 43, 41;
EXEC PRDB_Insertar_Episodios_Vistos 44, 44;
EXEC PRDB_Insertar_Episodios_Vistos 45, 46;
EXEC PRDB_Insertar_Episodios_Vistos 46, 50;
EXEC PRDB_Insertar_Episodios_Vistos 47, 45;
EXEC PRDB_Insertar_Episodios_Vistos 48, 48;
EXEC PRDB_Insertar_Episodios_Vistos 49, 47;
EXEC PRDB_Insertar_Episodios_Vistos 50, 49;
EXEC PRDB_Insertar_Episodios_Vistos 8, 31;
EXEC PRDB_Insertar_Episodios_Vistos 29, 37;
EXEC PRDB_Insertar_Episodios_Vistos 17, 39;

-- Inserción de Albumes guardados
EXEC PRDB_Insertar_Albumes_Guardados 1, 2;
EXEC PRDB_Insertar_Albumes_Guardados 1, 4;
EXEC PRDB_Insertar_Albumes_Guardados 2, 1;
EXEC PRDB_Insertar_Albumes_Guardados 3, 5;
EXEC PRDB_Insertar_Albumes_Guardados 4, 3;
EXEC PRDB_Insertar_Albumes_Guardados 4, 6;
EXEC PRDB_Insertar_Albumes_Guardados 5, 2;
EXEC PRDB_Insertar_Albumes_Guardados 6, 7;
EXEC PRDB_Insertar_Albumes_Guardados 6, 4;
EXEC PRDB_Insertar_Albumes_Guardados 7, 1;
EXEC PRDB_Insertar_Albumes_Guardados 8, 8;
EXEC PRDB_Insertar_Albumes_Guardados 9, 5;
EXEC PRDB_Insertar_Albumes_Guardados 10, 3;
EXEC PRDB_Insertar_Albumes_Guardados 11, 9;
EXEC PRDB_Insertar_Albumes_Guardados 12, 6;
EXEC PRDB_Insertar_Albumes_Guardados 13, 4;
EXEC PRDB_Insertar_Albumes_Guardados 14, 7;
EXEC PRDB_Insertar_Albumes_Guardados 15, 2;
EXEC PRDB_Insertar_Albumes_Guardados 16, 10;
EXEC PRDB_Insertar_Albumes_Guardados 17, 5;
EXEC PRDB_Insertar_Albumes_Guardados 18, 3;
EXEC PRDB_Insertar_Albumes_Guardados 19, 8;
EXEC PRDB_Insertar_Albumes_Guardados 20, 1;
EXEC PRDB_Insertar_Albumes_Guardados 21, 6;
EXEC PRDB_Insertar_Albumes_Guardados 22, 3;
EXEC PRDB_Insertar_Albumes_Guardados 23, 4;
EXEC PRDB_Insertar_Albumes_Guardados 24, 2;
EXEC PRDB_Insertar_Albumes_Guardados 25, 9;
EXEC PRDB_Insertar_Albumes_Guardados 26, 1;
EXEC PRDB_Insertar_Albumes_Guardados 27, 5;
EXEC PRDB_Insertar_Albumes_Guardados 28, 6;
EXEC PRDB_Insertar_Albumes_Guardados 29, 10;
EXEC PRDB_Insertar_Albumes_Guardados 30, 4;
EXEC PRDB_Insertar_Albumes_Guardados 31, 2;
EXEC PRDB_Insertar_Albumes_Guardados 32, 3;
EXEC PRDB_Insertar_Albumes_Guardados 33, 1;
EXEC PRDB_Insertar_Albumes_Guardados 34, 7;
EXEC PRDB_Insertar_Albumes_Guardados 35, 8;
EXEC PRDB_Insertar_Albumes_Guardados 36, 9;
EXEC PRDB_Insertar_Albumes_Guardados 37, 3;
EXEC PRDB_Insertar_Albumes_Guardados 38, 6;
EXEC PRDB_Insertar_Albumes_Guardados 39, 4;
EXEC PRDB_Insertar_Albumes_Guardados 40, 2;
EXEC PRDB_Insertar_Albumes_Guardados 41, 5;
EXEC PRDB_Insertar_Albumes_Guardados 42, 1;
EXEC PRDB_Insertar_Albumes_Guardados 43, 9;
EXEC PRDB_Insertar_Albumes_Guardados 44, 8;
EXEC PRDB_Insertar_Albumes_Guardados 45, 4;
EXEC PRDB_Insertar_Albumes_Guardados 46, 3;
EXEC PRDB_Insertar_Albumes_Guardados 47, 10;

-- Inserción de Podcast guardados
EXEC PRDB_Insertar_Podcast_Guardados 1, 5;
EXEC PRDB_Insertar_Podcast_Guardados 2, 17;
EXEC PRDB_Insertar_Podcast_Guardados 4, 11;
EXEC PRDB_Insertar_Podcast_Guardados 5, 26;
EXEC PRDB_Insertar_Podcast_Guardados 7, 3;
EXEC PRDB_Insertar_Podcast_Guardados 8, 14;
EXEC PRDB_Insertar_Podcast_Guardados 9, 21;
EXEC PRDB_Insertar_Podcast_Guardados 10, 2;
EXEC PRDB_Insertar_Podcast_Guardados 11, 9;
EXEC PRDB_Insertar_Podcast_Guardados 12, 33;
EXEC PRDB_Insertar_Podcast_Guardados 14, 6;
EXEC PRDB_Insertar_Podcast_Guardados 15, 18;
EXEC PRDB_Insertar_Podcast_Guardados 17, 19;
EXEC PRDB_Insertar_Podcast_Guardados 19, 30;
EXEC PRDB_Insertar_Podcast_Guardados 20, 8;
EXEC PRDB_Insertar_Podcast_Guardados 21, 15;
EXEC PRDB_Insertar_Podcast_Guardados 22, 34;
EXEC PRDB_Insertar_Podcast_Guardados 24, 25;
EXEC PRDB_Insertar_Podcast_Guardados 25, 28;
EXEC PRDB_Insertar_Podcast_Guardados 26, 7;
EXEC PRDB_Insertar_Podcast_Guardados 27, 35;
EXEC PRDB_Insertar_Podcast_Guardados 28, 1;
EXEC PRDB_Insertar_Podcast_Guardados 29, 16;
EXEC PRDB_Insertar_Podcast_Guardados 31, 24;
EXEC PRDB_Insertar_Podcast_Guardados 32, 22;
EXEC PRDB_Insertar_Podcast_Guardados 34, 39;
EXEC PRDB_Insertar_Podcast_Guardados 35, 10;
EXEC PRDB_Insertar_Podcast_Guardados 37, 46;
EXEC PRDB_Insertar_Podcast_Guardados 38, 47;
EXEC PRDB_Insertar_Podcast_Guardados 40, 20;
EXEC PRDB_Insertar_Podcast_Guardados 41, 50;
EXEC PRDB_Insertar_Podcast_Guardados 43, 13;
EXEC PRDB_Insertar_Podcast_Guardados 44, 27;
EXEC PRDB_Insertar_Podcast_Guardados 45, 48;
EXEC PRDB_Insertar_Podcast_Guardados 46, 4;
EXEC PRDB_Insertar_Podcast_Guardados 47, 38;
EXEC PRDB_Insertar_Podcast_Guardados 48, 31;
EXEC PRDB_Insertar_Podcast_Guardados 49, 32;
EXEC PRDB_Insertar_Podcast_Guardados 50, 29;
EXEC PRDB_Insertar_Podcast_Guardados 1, 41;
EXEC PRDB_Insertar_Podcast_Guardados 5, 43;
EXEC PRDB_Insertar_Podcast_Guardados 9, 45;
EXEC PRDB_Insertar_Podcast_Guardados 12, 36;
EXEC PRDB_Insertar_Podcast_Guardados 14, 42;
EXEC PRDB_Insertar_Podcast_Guardados 18, 49;
EXEC PRDB_Insertar_Podcast_Guardados 23, 44;
EXEC PRDB_Insertar_Podcast_Guardados 30, 12;
EXEC PRDB_Insertar_Podcast_Guardados 33, 23;
EXEC PRDB_Insertar_Podcast_Guardados 36, 37;
EXEC PRDB_Insertar_Podcast_Guardados 42, 40;
EXEC PRDB_Insertar_Podcast_Guardados 6, 19;
EXEC PRDB_Insertar_Podcast_Guardados 16, 15;

-- Inserción de Artistas favoritos
EXEC PRDB_Insertar_Artistas_Favoritos 1, 5;
EXEC PRDB_Insertar_Artistas_Favoritos 17, 3;
EXEC PRDB_Insertar_Artistas_Favoritos 12, 2;
EXEC PRDB_Insertar_Artistas_Favoritos 6, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 19, 20;
EXEC PRDB_Insertar_Artistas_Favoritos 50, 43;
EXEC PRDB_Insertar_Artistas_Favoritos 31, 14;
EXEC PRDB_Insertar_Artistas_Favoritos 44, 38;
EXEC PRDB_Insertar_Artistas_Favoritos 10, 27;
EXEC PRDB_Insertar_Artistas_Favoritos 5, 17;
EXEC PRDB_Insertar_Artistas_Favoritos 11, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 34, 3;
EXEC PRDB_Insertar_Artistas_Favoritos 9, 50;
EXEC PRDB_Insertar_Artistas_Favoritos 28, 30;
EXEC PRDB_Insertar_Artistas_Favoritos 1, 10;
EXEC PRDB_Insertar_Artistas_Favoritos 21, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 2, 2;
EXEC PRDB_Insertar_Artistas_Favoritos 35, 2;
EXEC PRDB_Insertar_Artistas_Favoritos 16, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 50, 50;
EXEC PRDB_Insertar_Artistas_Favoritos 47, 10;
EXEC PRDB_Insertar_Artistas_Favoritos 26, 39;
EXEC PRDB_Insertar_Artistas_Favoritos 14, 22;
EXEC PRDB_Insertar_Artistas_Favoritos 18, 8;
EXEC PRDB_Insertar_Artistas_Favoritos 4, 13;
EXEC PRDB_Insertar_Artistas_Favoritos 43, 36;
EXEC PRDB_Insertar_Artistas_Favoritos 7, 6;
EXEC PRDB_Insertar_Artistas_Favoritos 36, 6;
EXEC PRDB_Insertar_Artistas_Favoritos 36, 9;
EXEC PRDB_Insertar_Artistas_Favoritos 19, 5;
EXEC PRDB_Insertar_Artistas_Favoritos 42, 4;
EXEC PRDB_Insertar_Artistas_Favoritos 40, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 38, 30;
EXEC PRDB_Insertar_Artistas_Favoritos 37, 17;
EXEC PRDB_Insertar_Artistas_Favoritos 15, 10;
EXEC PRDB_Insertar_Artistas_Favoritos 32, 45;
EXEC PRDB_Insertar_Artistas_Favoritos 8, 26;
EXEC PRDB_Insertar_Artistas_Favoritos 3, 43;
EXEC PRDB_Insertar_Artistas_Favoritos 41, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 25, 11;
EXEC PRDB_Insertar_Artistas_Favoritos 12, 5;
EXEC PRDB_Insertar_Artistas_Favoritos 30, 50;
EXEC PRDB_Insertar_Artistas_Favoritos 24, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 22, 37;
EXEC PRDB_Insertar_Artistas_Favoritos 33, 9;
EXEC PRDB_Insertar_Artistas_Favoritos 46, 23;
EXEC PRDB_Insertar_Artistas_Favoritos 20, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 49, 40;
EXEC PRDB_Insertar_Artistas_Favoritos 27, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 48, 1;
EXEC PRDB_Insertar_Artistas_Favoritos 13, 19;
EXEC PRDB_Insertar_Artistas_Favoritos 29, 18;

-- Inserción de Albumes compuestos
EXEC PRDB_Insertar_Albumes_Compuestos 3, 21;
EXEC PRDB_Insertar_Albumes_Compuestos 25, 2;
EXEC PRDB_Insertar_Albumes_Compuestos 18, 45;
EXEC PRDB_Insertar_Albumes_Compuestos 41, 37;
EXEC PRDB_Insertar_Albumes_Compuestos 16, 3;
EXEC PRDB_Insertar_Albumes_Compuestos 10, 1;
EXEC PRDB_Insertar_Albumes_Compuestos 7, 9;
EXEC PRDB_Insertar_Albumes_Compuestos 22, 14;
EXEC PRDB_Insertar_Albumes_Compuestos 14, 5;
EXEC PRDB_Insertar_Albumes_Compuestos 32, 8;
EXEC PRDB_Insertar_Albumes_Compuestos 6, 31;
EXEC PRDB_Insertar_Albumes_Compuestos 23, 50;
EXEC PRDB_Insertar_Albumes_Compuestos 29, 42;
EXEC PRDB_Insertar_Albumes_Compuestos 45, 20;
EXEC PRDB_Insertar_Albumes_Compuestos 5, 48;
EXEC PRDB_Insertar_Albumes_Compuestos 33, 16;
EXEC PRDB_Insertar_Albumes_Compuestos 20, 44;
EXEC PRDB_Insertar_Albumes_Compuestos 11, 36;
EXEC PRDB_Insertar_Albumes_Compuestos 4, 12;
EXEC PRDB_Insertar_Albumes_Compuestos 19, 25;
EXEC PRDB_Insertar_Albumes_Compuestos 35, 17;
EXEC PRDB_Insertar_Albumes_Compuestos 31, 1;
EXEC PRDB_Insertar_Albumes_Compuestos 38, 46;
EXEC PRDB_Insertar_Albumes_Compuestos 43, 11;
EXEC PRDB_Insertar_Albumes_Compuestos 17, 50;
EXEC PRDB_Insertar_Albumes_Compuestos 12, 7;
EXEC PRDB_Insertar_Albumes_Compuestos 1, 10;
EXEC PRDB_Insertar_Albumes_Compuestos 48, 23;
EXEC PRDB_Insertar_Albumes_Compuestos 40, 43;
EXEC PRDB_Insertar_Albumes_Compuestos 7, 2;
EXEC PRDB_Insertar_Albumes_Compuestos 9, 34;
EXEC PRDB_Insertar_Albumes_Compuestos 36, 49;
EXEC PRDB_Insertar_Albumes_Compuestos 15, 33;
EXEC PRDB_Insertar_Albumes_Compuestos 47, 26;
EXEC PRDB_Insertar_Albumes_Compuestos 10, 18;
EXEC PRDB_Insertar_Albumes_Compuestos 2, 38;
EXEC PRDB_Insertar_Albumes_Compuestos 19, 35;
EXEC PRDB_Insertar_Albumes_Compuestos 26, 24;
EXEC PRDB_Insertar_Albumes_Compuestos 21, 41;
EXEC PRDB_Insertar_Albumes_Compuestos 18, 19;
EXEC PRDB_Insertar_Albumes_Compuestos 42, 6;
EXEC PRDB_Insertar_Albumes_Compuestos 3, 30;
EXEC PRDB_Insertar_Albumes_Compuestos 10, 29;
EXEC PRDB_Insertar_Albumes_Compuestos 6, 27;
EXEC PRDB_Insertar_Albumes_Compuestos 36, 32;

-- Inserción de Podcast locutados
EXEC PRDB_Insertar_Podcast_Locutados 3, 17;
EXEC PRDB_Insertar_Podcast_Locutados 15, 5;
EXEC PRDB_Insertar_Podcast_Locutados 1, 22;
EXEC PRDB_Insertar_Podcast_Locutados 18, 33;
EXEC PRDB_Insertar_Podcast_Locutados 7, 14;
EXEC PRDB_Insertar_Podcast_Locutados 25, 38;
EXEC PRDB_Insertar_Podcast_Locutados 30, 11;
EXEC PRDB_Insertar_Podcast_Locutados 21, 20;
EXEC PRDB_Insertar_Podcast_Locutados 12, 41;
EXEC PRDB_Insertar_Podcast_Locutados 49, 10;
EXEC PRDB_Insertar_Podcast_Locutados 40, 30;
EXEC PRDB_Insertar_Podcast_Locutados 4, 44;
EXEC PRDB_Insertar_Podcast_Locutados 22, 16;
EXEC PRDB_Insertar_Podcast_Locutados 50, 2;
EXEC PRDB_Insertar_Podcast_Locutados 35, 6;
EXEC PRDB_Insertar_Podcast_Locutados 9, 35;
EXEC PRDB_Insertar_Podcast_Locutados 14, 43;
EXEC PRDB_Insertar_Podcast_Locutados 37, 9;
EXEC PRDB_Insertar_Podcast_Locutados 17, 4;
EXEC PRDB_Insertar_Podcast_Locutados 5, 48;
EXEC PRDB_Insertar_Podcast_Locutados 46, 1;
EXEC PRDB_Insertar_Podcast_Locutados 38, 27;
EXEC PRDB_Insertar_Podcast_Locutados 23, 45;
EXEC PRDB_Insertar_Podcast_Locutados 19, 15;
EXEC PRDB_Insertar_Podcast_Locutados 43, 32;
EXEC PRDB_Insertar_Podcast_Locutados 36, 40;
EXEC PRDB_Insertar_Podcast_Locutados 13, 19;
EXEC PRDB_Insertar_Podcast_Locutados 11, 42;
EXEC PRDB_Insertar_Podcast_Locutados 42, 28;
EXEC PRDB_Insertar_Podcast_Locutados 16, 49;
EXEC PRDB_Insertar_Podcast_Locutados 28, 37;
EXEC PRDB_Insertar_Podcast_Locutados 10, 24;
EXEC PRDB_Insertar_Podcast_Locutados 2, 46;
EXEC PRDB_Insertar_Podcast_Locutados 48, 50;
EXEC PRDB_Insertar_Podcast_Locutados 32, 26;
EXEC PRDB_Insertar_Podcast_Locutados 27, 7;
EXEC PRDB_Insertar_Podcast_Locutados 20, 12;
EXEC PRDB_Insertar_Podcast_Locutados 26, 21;
EXEC PRDB_Insertar_Podcast_Locutados 33, 34;
EXEC PRDB_Insertar_Podcast_Locutados 45, 18;
EXEC PRDB_Insertar_Podcast_Locutados 24, 3;
EXEC PRDB_Insertar_Podcast_Locutados 44, 25;
EXEC PRDB_Insertar_Podcast_Locutados 6, 47;
EXEC PRDB_Insertar_Podcast_Locutados 29, 36;
EXEC PRDB_Insertar_Podcast_Locutados 39, 8;
EXEC PRDB_Insertar_Podcast_Locutados 8, 13;
EXEC PRDB_Insertar_Podcast_Locutados 41, 39;
EXEC PRDB_Insertar_Podcast_Locutados 31, 31;
EXEC PRDB_Insertar_Podcast_Locutados 34, 29;
EXEC PRDB_Insertar_Podcast_Locutados 47, 23;
EXEC PRDB_Insertar_Podcast_Locutados 18, 30;

-- Inserción de Episodios locutados
EXEC PRDB_Insertar_Episodios_Locutados 2, 8;
EXEC PRDB_Insertar_Episodios_Locutados 7, 15;
EXEC PRDB_Insertar_Episodios_Locutados 11, 4;
EXEC PRDB_Insertar_Episodios_Locutados 17, 22;
EXEC PRDB_Insertar_Episodios_Locutados 19, 3;
EXEC PRDB_Insertar_Episodios_Locutados 25, 10;
EXEC PRDB_Insertar_Episodios_Locutados 30, 11;
EXEC PRDB_Insertar_Episodios_Locutados 36, 27;
EXEC PRDB_Insertar_Episodios_Locutados 41, 12;
EXEC PRDB_Insertar_Episodios_Locutados 45, 19;
EXEC PRDB_Insertar_Episodios_Locutados 1, 1;
EXEC PRDB_Insertar_Episodios_Locutados 5, 14;
EXEC PRDB_Insertar_Episodios_Locutados 8, 6;
EXEC PRDB_Insertar_Episodios_Locutados 12, 39;
EXEC PRDB_Insertar_Episodios_Locutados 16, 9;
EXEC PRDB_Insertar_Episodios_Locutados 20, 18;
EXEC PRDB_Insertar_Episodios_Locutados 22, 40;
EXEC PRDB_Insertar_Episodios_Locutados 28, 2;
EXEC PRDB_Insertar_Episodios_Locutados 32, 25;
EXEC PRDB_Insertar_Episodios_Locutados 37, 23;
EXEC PRDB_Insertar_Episodios_Locutados 43, 21;
EXEC PRDB_Insertar_Episodios_Locutados 3, 45;
EXEC PRDB_Insertar_Episodios_Locutados 6, 17;
EXEC PRDB_Insertar_Episodios_Locutados 10, 35;
EXEC PRDB_Insertar_Episodios_Locutados 14, 24;
EXEC PRDB_Insertar_Episodios_Locutados 18, 5;
EXEC PRDB_Insertar_Episodios_Locutados 23, 16;
EXEC PRDB_Insertar_Episodios_Locutados 27, 7;
EXEC PRDB_Insertar_Episodios_Locutados 31, 41;
EXEC PRDB_Insertar_Episodios_Locutados 34, 36;
EXEC PRDB_Insertar_Episodios_Locutados 39, 28;
EXEC PRDB_Insertar_Episodios_Locutados 47, 48;
EXEC PRDB_Insertar_Episodios_Locutados 4, 30;
EXEC PRDB_Insertar_Episodios_Locutados 9, 42;
EXEC PRDB_Insertar_Episodios_Locutados 13, 44;
EXEC PRDB_Insertar_Episodios_Locutados 15, 50;
EXEC PRDB_Insertar_Episodios_Locutados 21, 33;
EXEC PRDB_Insertar_Episodios_Locutados 26, 13;
EXEC PRDB_Insertar_Episodios_Locutados 29, 43;
EXEC PRDB_Insertar_Episodios_Locutados 35, 26;
EXEC PRDB_Insertar_Episodios_Locutados 38, 46;
EXEC PRDB_Insertar_Episodios_Locutados 40, 31;
EXEC PRDB_Insertar_Episodios_Locutados 42, 20;
EXEC PRDB_Insertar_Episodios_Locutados 44, 47;
EXEC PRDB_Insertar_Episodios_Locutados 46, 32;
EXEC PRDB_Insertar_Episodios_Locutados 48, 37;
EXEC PRDB_Insertar_Episodios_Locutados 49, 38;
EXEC PRDB_Insertar_Episodios_Locutados 50, 34;
EXEC PRDB_Insertar_Episodios_Locutados 24, 49;
EXEC PRDB_Insertar_Episodios_Locutados 33, 29;

-- Inserción de Canciones compuestas
EXEC PRDB_Insertar_Canciones_Compuestas 12, 5;
EXEC PRDB_Insertar_Canciones_Compuestas 45, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 3, 1;
EXEC PRDB_Insertar_Canciones_Compuestas 50, 12;
EXEC PRDB_Insertar_Canciones_Compuestas 29, 22;
EXEC PRDB_Insertar_Canciones_Compuestas 7, 5;
EXEC PRDB_Insertar_Canciones_Compuestas 29, 17;
EXEC PRDB_Insertar_Canciones_Compuestas 4, 42;
EXEC PRDB_Insertar_Canciones_Compuestas 38, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 2, 31;
EXEC PRDB_Insertar_Canciones_Compuestas 23, 5;
EXEC PRDB_Insertar_Canciones_Compuestas 23, 16;
EXEC PRDB_Insertar_Canciones_Compuestas 19, 9;
EXEC PRDB_Insertar_Canciones_Compuestas 35, 15;
EXEC PRDB_Insertar_Canciones_Compuestas 17, 31;
EXEC PRDB_Insertar_Canciones_Compuestas 7, 17;
EXEC PRDB_Insertar_Canciones_Compuestas 1, 4;
EXEC PRDB_Insertar_Canciones_Compuestas 46, 1;
EXEC PRDB_Insertar_Canciones_Compuestas 39, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 32, 12;
EXEC PRDB_Insertar_Canciones_Compuestas 12, 15;
EXEC PRDB_Insertar_Canciones_Compuestas 37, 43;
EXEC PRDB_Insertar_Canciones_Compuestas 30, 20;
EXEC PRDB_Insertar_Canciones_Compuestas 15, 2;
EXEC PRDB_Insertar_Canciones_Compuestas 15, 4;
EXEC PRDB_Insertar_Canciones_Compuestas 48, 9;
EXEC PRDB_Insertar_Canciones_Compuestas 33, 8;
EXEC PRDB_Insertar_Canciones_Compuestas 18, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 42, 27;
EXEC PRDB_Insertar_Canciones_Compuestas 6, 12;
EXEC PRDB_Insertar_Canciones_Compuestas 44, 15;
EXEC PRDB_Insertar_Canciones_Compuestas 9, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 9, 2;
EXEC PRDB_Insertar_Canciones_Compuestas 50, 16;
EXEC PRDB_Insertar_Canciones_Compuestas 13, 3;
EXEC PRDB_Insertar_Canciones_Compuestas 41, 25;
EXEC PRDB_Insertar_Canciones_Compuestas 21, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 8, 1;
EXEC PRDB_Insertar_Canciones_Compuestas 26, 48;
EXEC PRDB_Insertar_Canciones_Compuestas 36, 10;
EXEC PRDB_Insertar_Canciones_Compuestas 24, 5;
EXEC PRDB_Insertar_Canciones_Compuestas 38, 13;
EXEC PRDB_Insertar_Canciones_Compuestas 17, 5;
EXEC PRDB_Insertar_Canciones_Compuestas 5, 33;
EXEC PRDB_Insertar_Canciones_Compuestas 43, 45;
EXEC PRDB_Insertar_Canciones_Compuestas 31, 5;
EXEC PRDB_Insertar_Canciones_Compuestas 27, 22;
EXEC PRDB_Insertar_Canciones_Compuestas 34, 1;
EXEC PRDB_Insertar_Canciones_Compuestas 28, 18;
EXEC PRDB_Insertar_Canciones_Compuestas 11, 40;
EXEC PRDB_Insertar_Canciones_Compuestas 49, 15;
